### ISSUE TITLE
reset() doesn't work 

### ISSUE THREAD

**Issue by kcris** [SRombauts/shared_ptr#1]
when resetting the pointer, the counter has to be updated too!

reset is incomplete, between acquire and release pn should be null (same as default ctor)

try code below and you'll see that A(2) is leaked

struct A
{
  A(int v = 0) : x(v) {}
  ~A() {std::cout << "destroying A.x=" << x << std::endl;} 
  int x;
};

int main()
{
  shared_ptr<A> sp1(new A(1));

  {
    shared_ptr<A> sp2(sp1);
    sp2.reset(new A(2)); //sp2 will leak
  }

  return 0;
}

**Comment by SRombauts** [comment]
Good question: it's a design choice, as stated just above in the comment:
`Assignment operator using the copy-and-swap idiom (copy constructor and swap method)`
