### ISSUE TITLE
GoogleTest submodule is no longer working

### ISSUE THREAD

**Issue by xsacha** [SRombauts/shared_ptr#2]
The submodule will no longer check out due to an issue in the chromium-hosted repo. Perhaps move to the github repo as the previous one is deprecated.

**Comment by SRombauts** [comment]
Hi @xsacha, I would gladly switch to the new github repo, but I never found the time to test this.

Did you? Can you provide a merge-request for that?

Cheers!

**Comment by xsacha** [comment]
I just changed it in .gitmodules and updated submodules and it worked (compiled) with latest master but I haven't used shared_ptr.

**Comment by xsacha** [comment]
Just ran the test and works fine:
[----------] Global test environment tear-down
[==========] 15 tests from 2 test cases ran. (23 ms total)
[  PASSED  ] 15 tests.

All I changed was the repo address for googletest in .gitmodules and then checked out master and added the new version.

**Comment by SRombauts** [comment]
Well, that's a good news, because as they changed the repository layout and the CMake files, I assumed there would be at least some configuration to redo!

I'll have a look into it soon, thanks again!
